### ISSUE TITLE
no re-ranking?

### ISSUE THREAD

**Issue by JonghwanMun** [kelvinxu/arctic-captions#11]
Actually, I know that re-ranking gives higher score (for m-RNN, about 3 points gain in terms of BLEU4 score and about 9 points in terms of CIDEr)
I'm wondering that this work does not use re-ranking as other works do? also, no any post-processing?

**Comment by ryankiros** [comment]
Hi JonghwanMun,

Our work came out a few months prior to Microsoft's nearest neighbour method and Junhua's consensus re-ranking idea. This is why re-ranking is not part of this project.

However, I have tried out Junhua's re-ranking method (not exactly the same, but similar) using our models and have gotten similar performance improvements with CIDEr.

**Comment by JonghwanMun** [comment]
@ryankiros 
Thanks for answering.
Is there an additional performance improvements on BLEU? (which is higher score than in paper - 70.7)
