### ISSUE TITLE
metrics.py reference format? 

### ISSUE THREAD

**Issue by xlhdh** [kelvinxu/arctic-captions#13]
The metrics.py scripts requires a path for the hypothesis files and one for the reference files. 
The format for the hypothesis file I assume is the file that is generated by generate_caps.py, but can you please explain the format of reference files, since there are like 5 sentences per image? 
Thank you!

**Comment by gamer13** [comment]
You could checkout my fork: https://github.com/gamer13/arctic-captions on how I did it. Basically I concatenate the GTs using a separator '<>' and in metric.py (not in my fork) do something like here: https://gist.github.com/gamer13/57500e6a250c378efccb

**Comment by kracwarlock** [comment]
metrics.py says len(hyp) = len(ref)
how does that work?
coco has 5 reference captions for each image but for each image we will have only one hypothesis caption

**Comment by kelvinxu** [comment]
I added the tokenized references to the repo. Hope that helps.

**Comment by kracwarlock** [comment]
Thanks Kelvin. I also figured out how to calculate metrics using a modified version of the coco caption script https://gist.github.com/kracwarlock/c979b10433fe4ac9fb97

You can close this issue now.

**Comment by kelvinxu** [comment]
Thanks Shikhar!
