### ISSUE TITLE
KeyError: 'A'

### ISSUE THREAD

**Issue by ervecherish** [kelvinxu/arctic-captions#15]
when run the prepare_data() in flickr30k.py ,it always reports an KeyError: 'A'.
Does it mean that my dictionary.pkl is incomplete?

**Comment by kelvinxu** [comment]
It would seem to indicate that. Did you do some kind of lowercasing in your preprocessing?

**Comment by evercherish** [comment]
i didn't modify the code, should i do lowercasing for the cc[0].split?
would you mind sharing your dictionary.pkl? i still think there are some problems with mine.
by the way, how long did it take you to train the flickr30k?how many epochs?
thx.

**Comment by kelvinxu** [comment]
No need to lowercase, shoot me your email.

**Comment by evercherish** [comment]
sword_cg@hotmail.com
thx!

**Comment by evercherish** [comment]
I guess you have been busy lately. I am sorry to bother you again, but I am really looking forward to your file. So could you please find a minute to send it recently? This e-mail address is available: sword_cg@hotmail.com
Best!

Date: Tue, 12 Jan 2016 07:59:26 -0800

**Comment by noureldien** [comment]
@ervecherish So, please what was the fix for this error? I also get it. Thank you.

**Comment by evercherish** [comment]
@noureldien  i have no idea either...i am waiting for xu's dictionary file, which i think may work for me.

**Comment by kelvinxu** [comment]
Sent.

**Comment by noureldien** [comment]
@ervecherish I'd appreciate if you get me involved (nreldien@yahoo.com), thank you.

**Comment by noureldien** [comment]
@kelvinxu I know you don't have to deal with this, but please how to create the dictionary? I've spent the whole weak (> 10 hrs a day) trying to get it working with no hope!! This is what I get when training on COCO using 'evalaute_coco.py'. Please help!

... Truth  0 :  UNK UNK filled UNK UNK cars and buildings UNK UNK UNK
Sample ( 0 )  0 : 
... Truth  1 :  UNK UNK UNK UNK boards UNK UNK hooks UNK UNK UNK
Sample ( 0 )  1 : 
... Truth  2 :  UNK dog UNK UNK UNK carpet UNK UNK UNK UNK UNK
Sample ( 0 )  2 : 
... Truth  3 :  an UNK UNK UNK UNK UNK book UNK filled UNK UNK
Sample ( 0 )  3 : 
... Truth  4 :  UNK UNK UNK at UNK building across UNK UNK from UNK
Sample ( 0 )  4 : 
... Truth  5 :  UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK UNK
Sample ( 0 )  5 : 
... Truth  6 :  closeup UNK UNK UNK UNK UNK has UNK UNK UNK UNK
Sample ( 0 )  6 : 
... Truth  7 :  UNK UNK UNK flying UNK UNK gas UNK UNK for UNK
Sample ( 0 )  7 : 
... Truth  8 :  UNK UNK UNK UNK UNK UNK UNK and holding UNK UNK
Sample ( 0 )  8 : 
... Truth  9 :  UNK UNK UNK UNK UNK UNK court holding UNK UNK UNK
Sample ( 0 )  9 :

**Comment by evercherish** [comment]
@kelvinxu thanks very very very…much, i've got it.

**Comment by parthchadha** [comment]
@kelvinxu @ Hi! Can you please share the dictionary file with me too! I have spent a lot of time and have not been able to solve the problem of KeyError and "coo_matrix' object does not support indexing".

My email id is "parth29@gmail.com"
