### ISSUE TITLE
RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by jnhwkim** [kelvinxu/arctic-captions#2]
<pre>/Users/Calvin/anaconda/lib/python2.7/site-packages/theano/scan_module/scan_perform_ext.py:133: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  from scan_perform.scan_perform import *</pre>

This is due to the my version of numpy? I googled about it but I can't get a good answer, though I found someone said it's just fine.

**Comment by kyunghyuncho** [comment]
@jnhwkim I think it should work fine regardlessly. @kelvinxu and I will look into it more.

**Comment by kelvinxu** [comment]
This should work fine, it is a harmless warning. You can read the full explanation here.

https://groups.google.com/forum/#!topic/theano-users/A__NVIBYMxA
