### ISSUE TITLE
Trained Models

### ISSUE THREAD

**Issue by ilkerkesen** [kelvinxu/arctic-captions#35]
I am not sure it is true way to ask this question, but have you published any pretrained models on any dataset?

**Comment by elliottd** [comment]
@ilkerkesen I have a [pretrained model and extracted features](https://github.com/elliottd/satyrid/blob/master/README.md#data--pre-trained-model) for the Flickr30K dataset. Hope this helps!

**Comment by ilkerkesen** [comment]
@elliottd thanks a lot!
