### ISSUE TITLE
question about "doubly stochastic attention"

### ISSUE THREAD

**Issue by zym1010** [kelvinxu/arctic-captions#38]
As I'm reading the paper, I don't understand, for the soft attention version, why we encourage `\sum_{t} a_{ti} \approx 1`, as I feel `C/L` would be more appropriate, since `\sum_{t,i} a_{ti} = C`.

**Comment by kelvinxu** [comment]
Hi, we have a note of this in the paper. What you suggest is correct, for the results we reported though we used 1. This didn't really change the results in our experience.

**Comment by zym1010** [comment]
@kelvinxu thanks!
