### ISSUE TITLE
Training parameters for Flickr30k, coco dataset?

### ISSUE THREAD

**Issue by hyunseokmin** [kelvinxu/arctic-captions#4]
Hello, thank you for sharing.

Shared source contains training parameters for Flickr8k dataset. 
Can I use the same parameters for Flickr30K and coco dataset? 

Thank you ^^;

**Comment by kelvinxu** [comment]
The `evaluate_coco.py` function should give you the parameters for MS COCO. For Flickr30k, you can just try playing with the hidden state size to something like 1300. You should get something similar.

**Comment by noureldien** [comment]
@hyunseokmin Please, did you manage to train the model on flickr_30k? What hyper-parameters did you use, please. Thank you.
