### ISSUE TITLE
Where can I get "model_name.npz" to run the Jupyter Notebook example?

### ISSUE THREAD

**Issue by leqo-c** [kelvinxu/arctic-captions#42]
Can you please provide a pretrained model on any of the three datasets (coco, flickr8k, flickr30k)? Or, at least, an indication on where to find it? 
I was trying to replicate the experiments in the Jupyter Notebook

**Comment by kelvinxu** [comment]
I haven't been able to find a consistent place to host models, so for the time being you are going to have to retrain your model from publically available datasets.
