### ISSUE TITLE
bias term has been added twice in LSTM layer

### ISSUE THREAD

**Issue by zhongwen** [kelvinxu/arctic-captions#7]
Both the codes in the function `_step(m_, x_, h_, c_)` from [here](https://github.com/kelvinxu/arctic-captions/blob/master/capgen.py#L240) and in computing `state_below` from [here](https://github.com/kelvinxu/arctic-captions/blob/master/capgen.py#L252) add the bias term, which seems to be wrong. Could you please have a look? Or if it is correct, could you please explain it a bit? Thx.

**Comment by kelvinxu** [comment]
Yeah this is an unnecessary add. I noticed it later but I forgot to fix it here. It shouldn't change the results but thanks for pointing it out!
