### ISSUE TITLE
Typo in the arXiv & ICML paper

### ISSUE THREAD

**Issue by zhongwen** [kelvinxu/arctic-captions#8]
From the [code](https://github.com/kelvinxu/arctic-captions/blob/master/capgen.py#L685) and Pascanu et. al, I think that Eqn 7 in the arXiv version (or Eqn 2 in the ICML version) should add a `tanh` after `L_0`.

And is a `y_t` missing in the same equation as well? From Bahdanau et al. Appendix part Page 14, `p(y_i | s_i, y_{i-1}, c_i)`

**Comment by kelvinxu** [comment]
We'll push an updated version of the paper to arxiv soon and clarify this. Thanks for pointing it out!
